FROM ros:jazzy

# Install build tools
RUN apt-get update && apt-get install -y \ 
  python3-colcon-common-extensions \
  python3-vcstool \
  clang-format \
  curl \
  pre-commit \
  nano \
  xvfb \
  x11vnc \
  netcat-traditional \
  ssh \
  apt-utils \
  net-tools \
  ros-jazzy-ros2-control \
  ros-jazzy-ros2-controllers \
  ros-jazzy-plotjuggler-ros \
  gedit \
  python3-pip \
  python3-venv \
  ros-jazzy-ur \
  python3-pandas
