FROM ros:jazzy

# Finding the right gazebo version: https://gazebosim.org/docs/harmonic/ros_installation/#summary-of-compatible-ros-and-gazebo-combinations

# Install build tools
RUN apt-get update && apt-get install -y \ 
  python3-colcon-common-extensions \
  python3-vcstool \
  clang-format \
  curl \
  pre-commit \
  nano \
  xvfb \
  x11vnc \
  netcat-traditional \
  ssh \
  apt-utils \
  net-tools \
  ros-jazzy-ros2-control \
  ros-jazzy-ros2-controllers \
  ros-jazzy-plotjuggler-ros \
  gedit \
  python3-pip \
  python3-venv \
  ros-jazzy-ur \
  python3-pandas \
  ros-jazzy-ros-gz \
  ros-jazzy-ur-client-library \
  ros-jazzy-ur \
  ros-jazzy-ur-simulation-gz \
  ros-jazzy-ur-controllers \
  ros-jazzy-ur-robot-driver
